import { SlideData } from './types'

export const DEFAULT_SLIDE_DATA: SlideData = {
  label: 'TONIGHT',
  labelWeight: 'regular',
  title: 'Wuthering Heights through the Ages',
  titleItalic: false,
  titleSize: 72,
  subtitle: 'with',
  subtitleWeight: 'regular',
  subtitleSize: 48,
  subtitleInline: false,
  subtitle2: '',
  subtitle2Weight: 'regular',
  subtitle2Size: 48,
  presenters: 'Vinson Cunningham,\nNaomi Fry\n& Alexandra Schwartz',
  presentersWeight: 'bold',
  presentersSize: 56,
  backgroundColor: '#000000',
  textColor: '#ffffff',
  accentColor: '#f5c842',
  imageUrl: '',
  imageAlt: 'Event logo',
  imageSize: 100,
  logos: [],
  logoSize: 60,
  showSeriesName: false,
  seriesName: 'RECANATI-KAPLAN TALKS',
  showListeningCredit: false,
  listeningCredit: 'Assistive listening devices made possible by Helen S. Rubinstein in memory of her father, Jack Rubinstein. Please speak with the house manager to pick up a device. They will be happy to assist you!',
}