import { SlideData } from './types'

export const DEFAULT_SLIDE_DATA: SlideData = {
  label: 'TONIGHT',
  labelWeight: 'regular',
  title: 'Wuthering Heights through the Ages',
  titleFont: '92NY',
  titleItalic: false,
  titleSize: 72,
  subtitle: 'with',
  subtitleWeight: 'regular',
  subtitleSize: 48,
  subtitleInline: false,
  subtitle2: '',
  subtitle2Weight: 'regular',
  subtitle2Size: 48,
  presenters: 'Vinson Cunningham,\nNaomi Fry\n& Alexandra Schwartz',
  presentersFont: 'Theinhardt',
  presentersItalic: false,
  presentersWeight: 'bold',
  presentersSize: 56,
  programTitle: '',
  programTitleFont: 'Theinhardt',
  programTitleWeight: 'regular',
  programTitleItalic: true,
  programTitleSize: 48,
  backgroundColor: '#000000',
  textColor: '#ffffff',
  accentColor: '#f5c842',
  imageMode: 'single' as const,
  imageUrl: '',
  imageAlt: '',
  imageSize: 100,
  staggerImages: [],
  imageOverlap: 30,
  staggerSize: 250,
  logos: [],
  logoSize: 60,
  showSeriesName: false,
  seriesName: 'RECANATI-KAPLAN TALKS',
  showListeningCredit: false,
  listeningCredit: 'Assistive listening devices made possible by Helen S. Rubinstein in memory of her father, Jack Rubinstein. Please speak with the house manager to pick up a device. They will be happy to assist you!',
}