// Auto-generated by scripts/fit_heuristic.py — DO NOT hand-edit the numbers below.
// Re-run that script against a fresh training_dataset.csv and paste the output here
// instead of tweaking values by hand.
//
// FIRST-PASS HEURISTIC — fit on a small training set (see the script's own console
// output for the exact row count and every group's sample size). This is deliberately
// simple grouped-average lookups, not a trained model — expect it to be refit/replaced
// as more /train data comes in. Treat suggestions as defaults, not ground truth.

export type ScreenTypeLike = 'projector' | 'lobby'
export type ImageTypeLike = 'book_cover' | 'face' | 'poster' | 'graphic' | 'other'

export interface SuggestedImagePosition {
  x: number
  y: number
  width: number
  height: number
  crop: 'none' | { top: number; bottom: number; left: number; right: number }
}

// Manual, non-fitted bump based on real usage feedback: the house style favors
// bigger/bolder titles than the historical sample's raw average. Tune this directly
// (not the bucket/nudge values inside suggestTitleFontSize) if that feedback changes.
const TITLE_SIZE_BIAS_PX = 20

/**
 * Suggest a title font size (px) from a small set of grouped-average lookups:
 * a primary bucket on chars-per-line, plus up to three secondary nudges (has_subtitle,
 * screen_type, image_1_type), each clamped to a modest +/-8px so no single weak signal
 * can dominate. Result is snapped to the nearest 4px, matching the granularity every
 * fitted value in the training set happened to share, and clamped to the real slider
 * range (24-160).
 */
export function suggestTitleFontSize(
  charCount: number,
  lineCount: number,
  screenType: ScreenTypeLike,
  hasSubtitle: boolean,
  imageType?: ImageTypeLike,
): number {
  const charsPerLine = lineCount > 0 ? charCount / lineCount : charCount

  let base: number
  if (charsPerLine <= 12) base = 92
  else if (charsPerLine <= 16) base = 76
  else base = 78

  const subtitleNudge = hasSubtitle ? 0 : -8

  const screenNudge: Record<ScreenTypeLike, number> = {
    lobby: 0,
    projector: -8,
  }

  const imageNudge: Partial<Record<ImageTypeLike, number>> = {
    book_cover: -2,
    face: 0,
    graphic: 0,
    poster: -8,
  }

  const rawFitted = base + subtitleNudge + screenNudge[screenType] + (imageType ? (imageNudge[imageType] ?? 0) : 0)
  const oldValue = Math.max(24, Math.min(160, Math.round(rawFitted / 4) * 4))

  // TITLE_SIZE_BIAS_PX is a manual, non-fitted bump (see its definition above) --
  // applied after the fitted bucket/nudge math, before the final snap+clamp.
  const snapped = Math.round((rawFitted + TITLE_SIZE_BIAS_PX) / 4) * 4
  const newValue = Math.max(24, Math.min(160, snapped))

  console.log(`[suggestTitleFontSize] old=${oldValue}px new=${newValue}px (bias=+${TITLE_SIZE_BIAS_PX}px)`)
  return newValue
}

/**
 * Suggest a subtitle font size (px). Unlike title, screen_type and line_count showed
 * no independent effect on subtitle_font_size_px in the fitted data (lobby/projector
 * medians were identical) — so this is intentionally just a char-count bucket lookup,
 * not padded with unused parameters.
 */
export function suggestSubtitleFontSize(charCount: number): number {
  let base: number
  if (charCount <= 10) base = 48
  else if (charCount <= 16) base = 36
  else base = 42
  return Math.max(16, Math.min(120, base))
}

const IMAGE_POSITION: Record<Exclude<ImageTypeLike, 'face'>, SuggestedImagePosition> = {
  book_cover: { x: 0.039, y: 0.061, width: 0.32, height: 0.867, crop: 'none' },
  poster: { x: 0.043, y: 0.04, width: 0.35, height: 0.92, crop: 'none' },
  graphic: { x: 0.26, y: 0.53, width: 0.225, height: 0.22, crop: 'none' },
  other: { x: 0.039, y: 0.061, width: 0.32, height: 0.867, crop: 'none' },
}

// Snapshot of 'other''s pre-tuning value (the pooled median across all image types),
// kept only so suggestImagePosition can log an old-vs-new comparison while sanity-
// checking the book_cover-matched bump above on real slides -- safe to delete once done.
const OLD_OTHER_POSITION: SuggestedImagePosition = { x: 0.035, y: 0.07, width: 0.32, height: 0.86, crop: 'none' }

// Faces showed two real position clusters in the fitted data (split on height_ratio
// > 0.6): near-full-height headshots vs. shorter/lower-placed ones. The split correlates
// only partially with screen_type (lobby has both; projector was consistently tall in
// this sample) — treated here as the closest single default per screen_type pending more data.
const FACE_POSITION: Record<ScreenTypeLike, SuggestedImagePosition> = {
  projector: { x: 0.024, y: 0.065, width: 0.339, height: 0.87, crop: { top: 0.05, bottom: 0.05, left: 0.05, right: 0.05 } },
  lobby: { x: 0.042, y: 0.465, width: 0.35, height: 0.48, crop: { top: 0.05, bottom: 0.05, left: 0.05, right: 0.05 } },
}

/**
 * Suggest a default position/size/crop for a newly-attached image, grouped by the
 * image's classified type (medians from the fitted data; 'other' is manually set to
 * match book_cover's proportions -- a normal-sized placeholder, not a thumbnail --
 * since no real image-type classification exists yet).
 * All values are ratios (0-1) relative to the full slide, matching the /train batch
 * prompt's image schema.
 */
export function suggestImagePosition(imageType: ImageTypeLike, screenType: ScreenTypeLike): SuggestedImagePosition {
  const result = imageType === 'face' ? FACE_POSITION[screenType] : IMAGE_POSITION[imageType]
  const old = imageType === 'other' ? OLD_OTHER_POSITION : result
  console.log(`[suggestImagePosition] imageType=${imageType} screenType=${screenType} old=`, old, 'new=', result)
  return result
}
